version: '3'

services:
  clients:
    image: 395454834028.dkr.ecr.us-east-1.amazonaws.com/builders:latest
    ports:
      - 8080:8080
    container_name: clients-back
    networks:
      - postgres-compose-network
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clients
    ports:
      - 5434:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
