version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clients
    ports:
      - 5434:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
